#### Viewing & Selecting Data

In [1]:
# Consider a DataFrame as similar to a dictionary of lists in Python.
people={
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Doe"],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com','JohnDoe@email.com']
}

In [2]:
people['email']

['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']

In [3]:
import pandas as pd

In [4]:
df=pd.DataFrame(people)

In [5]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [6]:
df['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [7]:
type(df['email']) 
# In Pandas, a DataFrame is not exactly like a Python list. Here, it returns a Series object, not a list.

pandas.core.series.Series

In [8]:
df.email 
# This execution yields the same result as df['email']. (Note: bracket notation is preferred to avoid method name conflicts).

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [9]:
df[['last','email']] 
# Note the double brackets [[]]. They cannot be omitted, otherwise an error will occur. The returned data type here is a DataFrame.

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com

In [10]:
df.columns # View all column names.

Index(['first', 'last', 'email'], dtype='object')

In [11]:
# View rows using iloc (integer-location based indexing).
df.iloc[0] # View the first row.

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: object

In [12]:
df.iloc[[0,1]] # View the first two rows.

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [13]:
df.iloc[[0,1],[2]] 
# View the 3rd column of the first two rows (rows 0, 1; column 2).

                     email
0  CoreyMSchafer@gmail.com
1        JaneDoe@email.com

In [14]:
df.loc[0] # View the first row. 'loc' stands for label-based location.

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: object

In [15]:
df.loc[[0,1]] # View the first two rows.

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [16]:
df.loc[[0,1], ['email']] # Same functionality as cell [14], but using labels.

                     email
0  CoreyMSchafer@gmail.com
1        JaneDoe@email.com

In [17]:
df.loc[[0,1], ['email', 'last']]

                     email     last
0  CoreyMSchafer@gmail.com  Schafer
1        JaneDoe@email.com      Doe

#### Index operations

In [18]:
# Set the 'email' column as the index for this DataFrame.
df.set_index('email')

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [19]:
df # Note that the original DataFrame 'df' remains unchanged. The previous operation returned a new DataFrame.

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [20]:
# To actually modify the index of the original DataFrame in place:
# df.set_index('email' , inplace=True)

In [21]:
df # Now the index has been permanently changed to 'email'.

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [22]:
#df.index

In [23]:
# df.loc['CoreyMSchafer@gmail.com','last']
# By setting 'email' as the index, we can now search using it. Since each email is unique, it acts like a primary key.

In [24]:
# Reset the modified index back to the default integer index.
# df.reset_index(inplace=True)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

#### Filtering data

In [25]:
df['last']=='Doe' # Filtering like this alone returns a boolean Series (mask).

0    False
1     True
2     True
Name: last, dtype: bool

In [26]:
filt=(df['last']=='Doe')
df[filt] # First, assign the boolean mask to a variable, then pass it to the DataFrame. The result is a filtered DataFrame.

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [27]:
df.loc[filt] # Yields the same result as above, using .loc is generally preferred for boolean indexing.

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [28]:
df.loc[filt,'email'] # Based on the filter, select and view only the 'email' column.

1    JaneDoe@email.com
2    JohnDoe@email.com
Name: email, dtype: object

In [29]:
filt=(df['last']=='Doe') & (df['first']=='John') # Use the '&' operator for 'AND' conditions.

In [30]:
df.loc[filt,'email']

2    JohnDoe@email.com
Name: email, dtype: object

In [31]:
filt1=(df['last']=='Schafer') | (df['first']=='John')
df.loc[filt1,'email']

0    CoreyMSchafer@gmail.com
2          JohnDoe@email.com
Name: email, dtype: object

In [32]:
df.loc[~filt1,'email'] # Use the '~' operator to negate the filter (i.e., return the opposite results).

1    JaneDoe@email.com
Name: email, dtype: object

#### Updating columns & values

In [33]:
df.columns #Display all columns

Index(['first', 'last', 'email'], dtype='object')

In [34]:
df.columns=['first_name','last_name','email'] # Rename all columns.

In [35]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [36]:
df.columns=[x.upper() for x in df.columns] # Convert all column names to uppercase using a list comprehension.
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [37]:
df.columns= df.columns.str.replace(' ','_') # Replace all spaces in column names with underscores.
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [38]:
df.columns=[x.lower() for x in df.columns]
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [39]:
df.rename(columns={'first_name':'first', 'last_name':'last'}) 
# Rename specific columns (Note: this does not change the original 'df' unless inplace=True is used).

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [40]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [41]:
df.rename(cdf.rename(columns={'first_name':'first', 'last_name':'last'},inplace=True) 
# Actually modify the column names in place.

SyntaxError: incomplete input (2880154615.py, line 2)

In [ ]:
df.loc[2]=['John','Smith','JohnSmith@email.com'] #modify all columns of one specific row
df

In [ ]:
df.loc[2]=['John','Smith','JohnSmith@email.com'] # Update the values of an entire row.
df

In [ ]:
df.loc[2,'last']='Smith'
df

In [ ]:
df.at[2,'last']='Doe' # Achieves the same functionality using .at, which is optimized for scalar values.

In [ ]:
filt=(df['email']=='JohnDoe@email.com')
# df[filt]['last']='Smith' # Common mistake: This will throw a SettingWithCopyWarning and the original 'df' will not be modified.

In [ ]:
filt=(df['email']=='JohnDoe@email.com')
df.loc[filt,'last']='Smith' # To modify values based on a condition, you must use .loc.
df

#### Using apply, map, replace

In [ ]:
df['email'].str.lower() 
# Display all emails converted to lowercase, but this does not alter the original DataFrame.
df

In [ ]:
df['email']=df['email'].str.lower() 
# Actually modify the DataFrame by assigning the lowercase values back to the column.
df

In [ ]:
df['email'].apply(len)

In [ ]:
def update_email(email):
    return email.upper()

In [ ]:
df['email'].apply(update_email)

In [ ]:
# Using a lambda function in Pandas.
df['email'].apply(lambda x: x.lower())

In [ ]:
df.apply(len) 
# Applying 'len' to a DataFrame returns the number of rows for each column.

In [ ]:
df.apply(pd.Series.min) 
# Here, 'min' returns the first value alphabetically for string columns.

In [ ]:
df.apply(lambda x: x.min()) # Same functionality using a lambda function.

In [ ]:
df.applymap(len) 
# 'applymap' applies a function to every individual element in the entire DataFrame. It cannot be used on a Series object.

In [ ]:
df.applymap(str.lower)

In [ ]:
# The 'map' method is used on a Series object, not a DataFrame.
df['first'].map({'Corey':'Chris','Jane':'Mary'})
# Values that are not mapped in the dictionary will be converted to NaN.

In [ ]:
df['first'].replace({'Corey':'Chris','Jane':'Mary'})
# Values that are not replaced will retain their original state.

#### Adding & Removing Data

In [ ]:
df['first']+' '+df['last'] # Concatenate values from two string columns.

In [ ]:
df['fullname']=(df['first']+' '+df['last']) # Add a new column with the concatenated values.
df

In [ ]:
df.drop(columns=['first','last']) # Drop two columns (the original DataFrame is not changed unless inplace=True).

In [ ]:
df['fullname'].str.split(' ') # Split the 'fullname' string into a list of substrings at each space.

In [ ]:
df['fullname'].str.split(' ',expand=True)

In [ ]:
df[['first','last']]=df['fullname'].str.split(' ',expand=True)
df

In [ ]:
df._append({'first':'Tony'},ignore_index=True) 
# Append a new row (dictionary) to the DataFrame. Note: pd.concat is preferred in newer Pandas versions.

In [ ]:
people={
    "first": ["Tony", "Steve"],
    "last": ["Stark", "Rpgers"],
    "email": ["IronMan@avenge.com", 'Cap@avenge.com']
}
df2=pd.DataFrame(people)
df2

In [ ]:
df._append(df2,ignore_index=True)
df

In [ ]:
df.drop(index=[4,5,6],inplace=True) # Drop specific rows by their index labels in place.

In [ ]:
df.drop(index=df[df['last']=='Doe'].index) # Drop rows where the 'last' name is 'Doe'.

In [ ]:
filt=df['last']=='Doe'
df.drop(index=df[filt].index) # Same effect, but storing the filter in a variable first improves readability.

In [ ]:
df.sort_values(by='last') #last name sorted aphabetically

In [ ]:
df.sort_values(by='last',ascending=False) #sort by descending orders

In [ ]:
df.sort_values(by=['last','first'],ascending=False) 
# Sort by 'last' first. If there are duplicates in 'last', then sort by 'first'.

In [ ]:
people={
    "first": ["Corey", "Jane", "John",'Adam'],
    "last": ["Schafer", "Doe", "Doe",'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com','JohnDoe@email.com','A@email.com']
}
df3=pd.DataFrame(people)
df3

In [ ]:
df3.sort_values(by=['last','first'],ascending=False)

In [ ]:
df3.sort_values(by=['last','first'],ascending=[False,True],inplace=True) 
# Sort 'last' in descending order, and 'first' in ascending order.
df

In [ ]:
df3.sort_index()

In [ ]:
# Sort a single Series object.
df3['last'].sort_values()

In [ ]:
import numpy as np

In [ ]:
people1={
    'first': ['Corey','Jane','John','Chirs', np.nan, None,'NA'],
    'last':['Schafer','Doe','Doe','Schafer',np.nan,np.nan,'Missing'],
    'email': ['CoreyMSchafer@gmail.com','JaneDoe@email.com','JohnDoe@email.com',None,np.nan,'Anonymous@email.com', 'NA'],
    'age':['33','55','63','36', None, None,'Missing']
}
df=pd.DataFrame(people1)
df

#### Handling Missing Data & Casting

In [ ]:
df.dropna() # Drop rows that contain any None or NaN values.

In [ ]:
df.dropna(axis='index', how='any') # Same effect, these are the default parameter values.

In [ ]:
df.dropna(axis='index', how='all') # Setting 'how' to 'all' means a row is only dropped if ALL of its values are None or NaN.

In [ ]:
df.dropna(axis='columns', how='all')  
# Setting 'axis' to 'columns' and 'how' to 'all' means a column is only dropped if ALL of its values are None or NaN.

In [ ]:
df.dropna(axis='columns', how='any')

In [ ]:
df.dropna(axis='index', how='any',subset=['email']) 
# Drop the row only if there is a missing value in the 'email' column. Missing values in other columns are ignored.

In [ ]:
df.dropna(axis='index', how='all',subset=['last','email'])
# Drop the row only if BOTH 'last' and 'email' are missing values. If one is present, the row is kept.

In [ ]:
df.replace('NA',np.nan,inplace=True)
df.replace('Missing',np.nan,inplace=True)
df

In [ ]:
df.isna() # Return a boolean mask indicating whether each value is NA (missing).

In [ ]:
df.fillna('Missing') # Replace all missing values (NaN/None) with the string 'Missing'.

In [ ]:
df.fillna(0)

In [ ]:
df.dtypes # Display the data types of all columns in the DataFrame.

In [ ]:
# df['age'].mean() 
# The mean() function cannot be used here because the 'age' column contains string types, not numeric types.

In [ ]:
df['age']= df['age'].astype(float) # Convert the 'age' column to float data type.
df.dtypes

In [ ]:
df['age'].mean()